myshop/cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('rosetta/', include('rosetta.urls')),
    path('', include('shop.urls', namespace='shop'))
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myshop/templates/includes/footer.html
{% load static %}
<div>© {{ year }} Copyright
  <p><span style="color:#f66a09">В</span>сякоРазно</p>
</div>

myshop/templates/includes/header.html
{% load i18n %}
{% load static %}
<div id="header">
  <a href="/" class="logo">{% trans 'ВсякоРазно' %}</a>
  {% get_current_language as LANGUAGE_CODE %}
  {% get_available_languages as LANGUAGES %}
  {% get_language_info_list for LANGUAGES as languages %}
  <div class="languages">
    <p>{% trans "Язык" %}:</p>
    <ul class="languages">
      {% for language in languages %}
        <li>
          <a href="/{{ language.code }}/"
            {% if language.code == LANGUAGE_CODE %} class="selected"{% endif %}>
            {{ language.name_local }}
          </a>
        </li>
      {% endfor %}
    </ul>
  </div>
</div>
<div id="subheader">
  <div class="cart">
    {% with total_items=cart|length %}
      {% if total_items > 0 %}
        {% trans 'Ваша корзина:' %}
        <a href="{% url "cart:cart_detail" %}">
          {{ total_items }} {% trans 'товаров, на сумму' %}
          {{ cart.get_total_price }} {% trans 'руб' %}
        </a>
      {% elif not order %}
        {% trans 'Ваша корзина пуста' %}
      {% endif %}
    {% endwith %}
  </div>
</div>